### ISSUE TITLE
Missing codes -129 and 4003

### ISSUE THREAD

**Issue by NicolaReed-Ometis** [countnazgul/qlik-internal-codes#1]
Stefan, you're missing my favourite undescribed error code!
-129 appears when the engine runs out of memory, and is usually seen when you are running a script with a cartesian join that generates a dataset bigger than the engine can handle.

I've also just had a client report an error code 4003 on Qlik Saas which just comes with the text "Operation Aborted" and I don't see this one on your list - if we figure out anything more on that one I'll let you know.

**Comment by countnazgul** [comment]
Thank you very much Nicola!

Both are added to the list.
